# 5.1 二维卷积层
**小结**:本节主要介绍了二维度卷积的概念,计算,可以通过训练得到卷积核的参数.
## 5.1.1 二维互相关运算
**小结**:本小结主要介绍了二维卷积的概念及其计算过程.

In [1]:
import torch 
from torch import nn

print(torch.__version__)

1.0.0


**功能**:输入数组X与核函数K,并输出数组Y

In [2]:
def corr2d(X, K):  # 本函数已保存在d2lzh_pytorch包中方便以后使用
    X = X.float()
    K = K.float()
    Y = torch.empty(X.shape[0]-K.shape[0] + 1, X.shape[1]-K.shape[1] + 1)
    for j in range(Y.shape[0]):
        for i in range(Y.shape[1]):
            Y[j][i]=(X[j:j+K.shape[0],i:i+K.shape[1]]*K[:,:]).sum()
    return Y

In [3]:
X = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
K = torch.tensor([[0, 1], [2, 3]])
corr2d(X, K)

tensor([[19., 25.],
        [37., 43.],
        [55., 61.]])

## 5.1.2 二维卷积层
**小结**:本小节主要实现了一个自定义的二维卷积层.

In [4]:
class Conv2D(nn.Module):
    def __init__(self, kernel_size):
        super(Conv2D, self).__init__()
        self.weight = nn.Parameter(torch.randn(kernel_size))
        self.bias = nn.Parameter(torch.randn(1))

    def forward(self, x):
        return corr2d(x, self.weight) + self.bias

## 5.1.3 图像中物体边缘检测
**小结**:本小节介绍了利用一个卷积层可以检测图像中物体的边缘,即找到像素变化的位置.

In [5]:
X = torch.ones(6, 8)
X[:, 2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [6]:
K = torch.tensor([[1, -1]])

In [7]:
Y = corr2d(X, K)
Y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

## 5.1.4 通过数据学习核数组
**小结**:本小结主要介绍了通过数据学习核数组,其中代价函数是平方误差,学习方法是梯度下降法.

In [8]:
# 构造一个核数组形状是(1, 2)的二维卷积层
conv2d = Conv2D(kernel_size=(1, 2))

step = 20
lr = 0.01
for i in range(step):
    Y_hat = conv2d(X)
    l = ((Y_hat - Y) ** 2).sum()
    l.backward()
    
    # 梯度下降
    conv2d.weight.data -= lr * conv2d.weight.grad
    conv2d.bias.data -= lr * conv2d.bias.grad
    
    # 梯度清0
    conv2d.weight.grad.fill_(0)
    conv2d.bias.grad.fill_(0)
    if (i + 1) % 5 == 0:
        print('Step %d, loss %.3f' % (i + 1, l.item()))

Step 5, loss 1.633
Step 10, loss 0.453
Step 15, loss 0.126
Step 20, loss 0.035


In [9]:
print("weight: ", conv2d.weight.data)
print("bias: ", conv2d.bias.data)

weight:  tensor([[ 0.9529, -0.9519]])
bias:  tensor([-0.0006])
