# torch.nn.init
**小结**:`torch.nn.init`的功能是进行参数初始化

In [1]:
import torch
import torch.nn as nn

In [2]:
# 均匀分布U(a,b)中生成值,填充输入的张量
w = torch.Tensor(3, 5)
print(nn.init.uniform_(w, a = 2, b = 3))

tensor([[2.7578, 2.6735, 2.2860, 2.7246, 2.7137],
        [2.8028, 2.5002, 2.2517, 2.0424, 2.9130],
        [2.5490, 2.9969, 2.4518, 2.2212, 2.6591]])


In [3]:
# 正态分布
w = torch.Tensor(6,8)
print(nn.init.normal_(w, mean = 10, std = 0.01))

tensor([[10.0002, 10.0086, 10.0133,  9.9989, 10.0086, 10.0026,  9.9900,  9.9964],
        [10.0016, 10.0071, 10.0048,  9.9846,  9.9953,  9.9965, 10.0010,  9.9813],
        [10.0038,  9.9989, 10.0020, 10.0125,  9.9940, 10.0095, 10.0085,  9.9998],
        [10.0005, 10.0057,  9.9983,  9.9937,  9.9923,  9.9853, 10.0041,  9.9986],
        [10.0017,  9.9938, 10.0059,  9.9988,  9.9866,  9.9975, 10.0042,  9.9950],
        [ 9.9780,  9.9949,  9.9879, 10.0105, 10.0011,  9.9969, 10.0119, 10.0232]])


In [4]:
# 常量
w = torch.Tensor(8,8)
print(nn.init.constant_(w, val = 6))

tensor([[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]])
