# torch
**小结**:  
包 torch 包含了多维张量的数据结构以及基于其上的多种数学操作。另外，它也提供了多种工具，其中一些可以更有效地对张量和任意类型进行序列化。  

**列表**:  
`torch.mean()`  
`torch.ones()`  
`.size()`

In [1]:
import torch
import torch.nn as nn

## torch.mean

In [2]:
a = torch.Tensor([[1,2],[3,4]])

In [3]:
torch.mean(a)

tensor(2.5000)

In [4]:
# 归到1行
torch.mean(a, 0, keepdim=True)

tensor([[2., 3.]])

In [5]:
# 归到1列
torch.mean(a, 1, keepdim=True)

tensor([[1.5000],
        [3.5000]])

In [6]:
torch.mean(a.data, 1, keepdim=True)

tensor([[1.5000],
        [3.5000]])

## `torch.ones`和`.size()`

In [7]:
data = torch.Tensor([[3,4],[5,6]])
torch.ones(data.size())

tensor([[1., 1.],
        [1., 1.]])