## 小结
gather的主要的功能是通过索引的方式将我们需要的元素gather(聚集)到一起得到新的tensor。
## 参考资料
Pytorch的gather用法理解 https://www.cnblogs.com/HongjianChen/p/9451526.html

In [1]:
import torch
import torchvision
import numpy as np
import sys

print(torch.__version__)
print(torchvision.__version__)

1.0.0
0.2.2


In [2]:
a = torch.arange(0,16).view(4,4)

In [3]:
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [4]:
# 选取对角线的元素
index0 = torch.LongTensor([[0,1,2,3]])

In [5]:
a.gather(0,index0)

tensor([[ 0,  5, 10, 15]])

In [6]:
# 选取任意行号的元素
index1 = torch.LongTensor([[3,1,1,2]])

In [7]:
a.gather(0,index1)

tensor([[12,  5,  6, 11]])

In [8]:
# 选取反对角线上的元素
index2 = torch.LongTensor([[3,2,1,0]])

In [9]:
a.gather(0,index2)

tensor([[12,  9,  6,  3]])