# torch.unsqueeze() 和 torch.squeeze()
**小结**：这两个PyTorch API是为了进行维度的解压和压缩。
## 参考资料
[1][torch.unsqueeze() 和 torch.squeeze()](https://zhuanlan.zhihu.com/p/86763381)

In [1]:
import torch

x = torch.Tensor([1, 2, 3, 4])  # torch.Tensor是默认的tensor类型（torch.FlaotTensor）的简称。

print('-' * 50)
print(x)  # tensor([1., 2., 3., 4.])
print(x.size())  # torch.Size([4])
print(x.dim())  # 1
print(x.numpy())  # [1. 2. 3. 4.]

--------------------------------------------------
tensor([1., 2., 3., 4.])
torch.Size([4])
1
[1. 2. 3. 4.]


Q：如何理解`torch.unsqueeze()`的行列扩展模式？  
A：关键是理解下图。  
原因：方便操作
0(-2)-行扩展
1(-1)-列扩展
正向：我们在0，1位置上扩展
逆向：我们在-2，-1位置上扩展
维度扩展：1维->2维，2维->3维，...，n维->n+1维
维度降低：n维->n-1维，n-1维->n-2维，...，2维->1维

以 1维->2维 为例，

从【正向】的角度思考：

torch.Size([4])
最初的 tensor([1., 2., 3., 4.]) 是 1维，我们想让它扩展成 2维，那么，可以有两种扩展方式：

一种是：扩展成 1行4列 ，即 tensor([[1., 2., 3., 4.]])
针对第一种，扩展成 [1, 4]的形式，那么，在 dim=0 的位置上添加 1

另一种是：扩展成 4行1列，即
tensor([[1.],
        [2.],
        [3.],
        [4.]])
针对第二种，扩展成 [4, 1]的形式，那么，在dim=1的位置上添加 1

从【逆向】的角度思考：
原则：一般情况下， "-1" 是代表的是【最后一个元素】
在上述的原则下，
扩展成[1, 4]的形式，就变成了，在 dim=-2 的的位置上添加 1
扩展成[4, 1]的形式，就变成了，在 dim=-1 的的位置上添加 1
![示意图](https://pic1.zhimg.com/80/v2-c4e34129975b40e7ac9cacbb67c9c904_720w.jpg)

# 1.`torch.unsqueeze`详解

### torch.unsqueeze（）参数设0，行扩展

In [2]:
print('-' * 50)
print(torch.unsqueeze(x, 0))  # tensor([[1., 2., 3., 4.]])
print(torch.unsqueeze(x, 0).size())  # torch.Size([1, 4])
print(torch.unsqueeze(x, 0).dim())  # 2
print(torch.unsqueeze(x, 0).numpy())  # [[1. 2. 3. 4.]]

--------------------------------------------------
tensor([[1., 2., 3., 4.]])
torch.Size([1, 4])
2
[[1. 2. 3. 4.]]


### torch.unsqueeze（）参数设1，列扩展

In [3]:
print('-' * 50)
print(torch.unsqueeze(x, 1))
print(torch.unsqueeze(x, 1).size())  # torch.Size([4, 1])
print(torch.unsqueeze(x, 1).dim())  # 2

--------------------------------------------------
tensor([[1.],
        [2.],
        [3.],
        [4.]])
torch.Size([4, 1])
2


### torch.unsqueeze（）参数设-1，列扩展

In [4]:
print('-' * 50)
print(torch.unsqueeze(x, -1))
print(torch.unsqueeze(x, -1).size())  # torch.Size([4, 1])
print(torch.unsqueeze(x, -1).dim())  # 2

--------------------------------------------------
tensor([[1.],
        [2.],
        [3.],
        [4.]])
torch.Size([4, 1])
2


### torch.unsqueeze（）参数设-2，行扩展

In [5]:
print('-' * 50)
print(torch.unsqueeze(x, -2))  # tensor([[1., 2., 3., 4.]])
print(torch.unsqueeze(x, -2).size())  # torch.Size([1, 4])
print(torch.unsqueeze(x, -2).dim())  # 2

--------------------------------------------------
tensor([[1., 2., 3., 4.]])
torch.Size([1, 4])
2


In [6]:
# 边界测试
# 说明：A dim value within the range [-input.dim() - 1, input.dim() + 1) （左闭右开）can be used.
#print('-' * 50)
#print(torch.unsqueeze(x, -3))
#IndexError: Dimension out of range (expected to be in range of [-2, 1], but got -3)

# print('-' * 50)
# print(torch.unsqueeze(x, 2))
# IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

## 2.torch.squeeze详解
**作用**：降维
torch.squeeze(input, dim=None, out=None)

将输入张量形状中的1 去除并返回。 如果输入是形如(A×1×B×1×C×1×D)，那么输出形状就为： (A×B×C×D)

当给定dim时，那么挤压操作只在给定维度上。例如，输入形状为: (A×1×B), squeeze(input, 0) 将会保持张量不变，只有用 squeeze(input, 1)，形状会变成 (A×B)。

注意： 返回张量与输入张量共享内存，所以改变其中一个的内容会改变另一个。  
参数:  
input (Tensor) – 输入张量  
dim (int, optional) – 如果给定，则input只会在给定维度挤压  
out (Tensor, optional) – 输出张量    
Q：为何只去掉 1 呢？  
A：多维张量本质上就是一个变换，如果维度是 1 ，那么，1 仅仅起到扩充维度的作用，而没有其他用途，因而，在进行降维操作时，为了加快计算，是可以去掉这些 1 的维度。

In [7]:
print("*" * 50)

m = torch.zeros(2, 1, 2, 1, 2)
print(m.size())

**************************************************
torch.Size([2, 1, 2, 1, 2])


In [8]:
n = torch.squeeze(m)
print(n)
print(n.size())

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
torch.Size([2, 2, 2])


In [9]:
n = torch.squeeze(m, 0)  # 当给定dim时，那么挤压操作只在给定维度上
print(n)
print(n.size())

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
torch.Size([2, 1, 2, 1, 2])


In [10]:
n = torch.squeeze(m, 1)
print(n.size())

torch.Size([2, 2, 1, 2])


In [11]:
n = torch.squeeze(m, 2)
print(n.size())

torch.Size([2, 1, 2, 1, 2])


In [12]:
n = torch.squeeze(m, 3)
print(n.size())  # torch.Size([2, 1, 2, 2])

torch.Size([2, 1, 2, 2])


In [13]:
print("@" * 50)
p = torch.zeros(2, 1, 1)
print(p)
print(p.numpy())
print(p.size())

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
tensor([[[0.]],

        [[0.]]])
[[[0.]]

 [[0.]]]
torch.Size([2, 1, 1])


In [14]:
q = torch.squeeze(p)
print(q)
print(q.numpy())
print(q.size())
print(torch.zeros(3, 2).numpy())

tensor([0., 0.])
[0. 0.]
torch.Size([2])
[[0. 0.]
 [0. 0.]
 [0. 0.]]
